# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - clavefoodbot

on:
    push:
        branches:
            - feature/12-azure-hosting
    workflow_dispatch:

jobs:
    buildweb:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: install dependencies
              uses: borales/actions-yarn@v3.0.0
              with:
                  working-directory: ${GITHUB_WORKSPACE}/web
                  cmd: install

            - name: build
              uses: borales/actions-yarn@v3.0.0
              with:
                  working-directory: ${GITHUB_WORKSPACE}/web
                  cmd: build:production

    deployweb:
        runs-on: ubuntu-latest
        needs: buildweb

        steps:
            - uses: actions/checkout@v2
            - uses: azure/login@v1
              with:
                  creds: ${{ secrets.STOREWEB_AZURE_CREDENTIALS }}

            - name: Upload to blob storage
              uses: azure/CLI@v1
              with:
                  working-directory: ${GITHUB_WORKSPACE}/web
                  inlineScript: |
                      az storage blob upload-batch --account-name storewebclaveplatformer --auth-mode key -d '$web' -s ${GITHUB_WORKSPACE}/web/dist

            # Azure logout
            - name: logout
              run: |
                  az logout
              if: always()

    buildapi:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up .NET Core
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: "6.0.x"
                  include-prerelease: true

            - name: Build with dotnet
              run: dotnet build  --configuration Release  ${GITHUB_WORKSPACE}/api/ClavePlatformer.csproj

            - name: dotnet publish
              run: dotnet publish ${GITHUB_WORKSPACE}/api/ClavePlatformer.csproj -c Release -o ClavePlatformerApi

            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v2
              with:
                  name: ClavePlatformerApi
                  path: ClavePlatformerApi

    deployapi:
        runs-on: ubuntu-latest
        needs: buildapi
        environment:
            name: "Production"
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v2
              with:
                  name: ClavePlatformerApi

            - name: Deploy to Azure Web App
              id: deploy-to-webapp
              uses: Azure/functions-action@v1
              with:
                  app-name: "func-clave-platformer"
                  slot-name: "Production"
                  publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
                  package: .
